#!/usr/bin/python
filelist = list()
with open("Maths_Marks", 'r') as fp:
        fp = fp.readlines()
        for line in fp:
            print line
            tmpLine = line.split(",")
            sname = tmpLine[0]
            fname = tmpLine[1]
            marks = tmpLine[2]
            if int(marks) not in range(0,100):
                GroupNumber = "Invalid Mark"
            elif int(marks) >= 90:
                GroupNumber = "10M1"
            elif int(marks) >= 80:
                GroupNumber = "10M2"
            elif int(marks) >= 70:
                GroupNumber = "10M3"
            elif int(marks) >= 60:
                GroupNumber = "10M4"
            elif int(marks) >= 50:
                GroupNumber = "10M5"
            elif int(marks) >= 40:
                GroupNumber = "10M6"
            elif int(marks) >= 30:
                GroupNumber = "10M7"
            elif int(marks) >= 20:
                GroupNumber = "10M8"
            elif int(marks) >= 10:
                GroupNumber = "10M9"
            line = line.strip() + "," + GroupNumber
            filelist.append(line.strip())

with open("JK",'w') as s:
     for line  in filelist:
         print line
         print >> s, line
